message:
  prefix: "&x&f&b&7&4&5&6&lA&x&f&a&8&b&5&d&lU&x&f&8&a&2&6&5&lC&x&f&7&b&9&6&c&lT&x&f&6&c&f&7&3&lI&x&f&4&e&6&7&b&lO&x&f&3&f&d&8&2&lN&7 »&r "
  auction-start: "\n      &e☆ &a☆ &b★     &6☜ &x&f&b&7&4&5&6&lA&x&f&a&8&b&5&d&lU&x&f&8&a&2&6&5&lC&x&f&7&b&9&6&c&lT&x&f&6&c&f&7&3&lI&x&f&4&e&6&7&b&lO&x&f&3&f&d&8&2&lN&7&r &6☞      &b★ &a☆ &e☆ \n\n&d• &fการประมูล &a{item}&f ได้เริ่มขึ้นแล้ว!\n&d• &bราคาขั้นต่ำเริ่มต้นที่ &e{price} &6⛃\n&d• &c/auction view &eเพื่อดูตัวอย่างไอเท็ม\n&d• &c/auction bid [จำนวนเงิน] &eเพื่อเริ่มบิต\n&d• &7กรุณาเครียไอเท็มในช่องเก็บของของคุณ\n"
  auction-bid-success: "&b&l{player} &aได้ต่อรองราคาไว้ที่ &e{price} &6⛃ &7(ราคาขั้นต่ำต่อไปคือ &e{next price} &6⛃&7)"
  auction-bid-price: "&cจำนวนเงินของคุณน้อยเกินไปที่จะลงประมูล! &7(ขั้นต่ำ &c{price}&7)"
  auction-not-start: "&cการประมูลยังไม่เริ่มขึ้น!"
  auction-already-bid: "&cคุณได้บิดของชิ้นนี้ไปแล้ว กรุณารอคนบิดคนต่อไป"
  auction-already-start: "&cการประมูลเปิดอยู่!"
  not-enough-money: "&cคุณมีเงินไม่มากพอสำหรับการบิด!"
  auction-count-down: "&aการประมูล &f[&e{item}&f] &aจะจบลงใน &c{time} &e/auction bid [จำนวนเงิน]"
  auction-few-count-down: "&aการประมูลจะจบลงใน &c{time}"
  auction-master-not-enough-money: "&cAuction Master ขณะนี้มีเงินไม่เพียงพอ ระบบจะยึดตามคนที่บิดสูงสุดคนก่อนเป็นหลัก"
  auction-master-offline: "&cAuction Master ได้ออกจากเซิฟไปแล้ว ระบบจะยึดตามคนที่บิดสูงสุดคนก่อนเป็นหลัก"
  auction-end: "&aการประมูลได้จบลงแล้ว!"
  auction-no-bidder: "&cการประมูลนี้ไม่มีผู้เข้าร่วมประมูล"
  auction-winner: "&aผู้เล่นที่ได้รับของจากการประมูลคือ &b{player} &aด้วยราคา &e{price} &6⛃"
  auction-cancelled: "&cการประมูลนี้ถูกยกเลิกแล้ว ขออภัยในความไม่สะดวก"
  syntax-error: "&cคำสั่งไม่ถูกต้อง!"
  no-item: "&cคุณต้องถือไอเท็มไว้ในมือ!"
  specify-price: "&cกรุณาระบุราคาให้ถูกต้อง"
  system-error: "&cเกิดข้อผิดพลาดของระบบ ขออภัยในความไม่สะดวก"
  invalid-number: "&cกรุณาใส่ตัวเลขให้ถูกต้อง"
  no-permission: "&cคุณไม่สามารถใช้งานคำสั่งนี้ได้"
  placeholder-no-bidder: "&cยังไม่มีผู้ประมูล"
  time-format:
    second: "วินาที"
    minute: "นาที"
    hour: "ชั่วโมง"


auction:
  default-duration: 45
  default-scale: 10.0
  message-at-interval: [75, 60, 45, 30 ,15, 10]

view-auction:
  title: "Auction Item"
  size: 27
  border:
    type: GOLD_NUGGET
    model: 7009
  auction-item-slot: 13
